export const SET_PROGRAM = "SET_PROGRAM";
export const FETCH_PROGRAM_FAILED = "FETCH_PROGRAM_FAILED";

export const SET_STRATEGY = "SET_STRATEGY";
export const FETCH_STRATEGY_FAILED = "FETCH_STRATEGY_FAILED";